### ISSUE TITLE
Implement GET getFederationList and cache list

### ISSUE THREAD

**Issue by nikzen** [famedly/synapse-invite-checker#5]
### Description
We need to fetch and cache the federation list to validate the outbound traffic. This document is fully based on the gematik spec.

### Flow description
- The federation list needs to be updated at least every hour (ML-137902 - AF_10064)
- If the domain is not part of the federation list, we need to check if this is the latest federation list

### Authentication
- The endpoint will be protected using mTLS
```[tasklist]
### Tasks
- [ ] Implement mTLS to call vzd-fhir-directory-proxy-api
- [ ] Fetch and cache federation list
- [ ] Build logic to check for latest version if destination url is not part of the federation list
```
